build:
  cuda_version: "12.1.1"
  python_packages:
    - "torch==2.1.2"
    - "vllm==0.2.6"
    - "transformers==4.36.2"
    - "accelerate==0.25.0"
    - "hf-transfer==0.1.9"
    - "huggingface-hub==0.29.1"
